### ISSUE TITLE
[Feature] enable dropping spell effects

### ISSUE THREAD

**Issue by manuel-hegner** [reonZ/pf2e-giveth#2]
Could you expand this awesome module to also enable players to apply spell effects to other tokens?

**Comment by reonZ** [comment]
This is not a bad idea, i have quite the backlog though so i dunno when i will be able to look into it.

**Comment by reonZ** [comment]
With version `1.2.0`, the module now allows players to drag & drop effects and conditions that originated from them onto other player-owned actors (the effect will lose its `unidentified` status and will have its `showIcon` set to `true` to avoid any possible weirdness)
