### ISSUE TITLE
Pf2e Giveth still has the "You are not allowed to move items to this character." bug

### ISSUE THREAD

**Issue by xavien12** [reonZ/pf2e-giveth#9]
After disabling all modules other than pf2e giveth, the items could still not be moved by players.

**Comment by reonZ** [comment]
I just tested with the installed version of the module (not my local one) and it works on my end.

PF2e system `4.11.1` & PF2e Giveth `1.3.4` (are you maybe still using the `4.11.0` of the system ?)

https://user-images.githubusercontent.com/651462/235445101-101a8aff-027d-4fc5-a59b-bc7ef9cc89b8.mp4

**Comment by xavien12** [comment]
I am using the 4.11.1. Can you check under "configure ownership" for each character involved to see if they are owned by different players. I have each character as all players "limited" and they are only "Owner" of their own character.

**Comment by reonZ** [comment]
The character from which the item was dragged:

![Foundry_Virtual_Tabletop_FjwQSttrKQ](https://user-images.githubusercontent.com/651462/235496992-19959bc7-c9b4-4e8e-9f0a-d6a8f6bfaa6c.jpg)

The receiving character:

![image](https://user-images.githubusercontent.com/651462/235497136-b03c4dc7-f7b4-4b23-b1c7-d9e480d1d14f.png)

The module checks if the actor is owned by any player, if it is not a synthetic actor (so unlinked actors won't work) and if it is either a `Character`, `NPC` or `Vehicle`. So it doesn't really matter anyways.



Maybe try to uninstall (delete the directory) the module and re-install it.

**Comment by xavien12** [comment]
I uninstalled and re-installed pf2e-giveth. I created a new world with all modules but pf2e-giveth deactivated
![Giveth3](https://user-images.githubusercontent.com/58941502/235681358-10e497d0-6937-4ff7-8e3c-1b23687e9644.png)

I created 2 players

![Giveth1](https://user-images.githubusercontent.com/58941502/235681507-34873e90-692b-4820-873f-165a6368a00d.png)
![Giveth2](https://user-images.githubusercontent.com/58941502/235681528-69da3ef0-1181-4429-8bb3-c0a5822c48c1.png)

I tried moving a single health potion and then an alabaster idol from one of them to the other
I still got the error message.
![giveth4](https://user-images.githubusercontent.com/58941502/235681724-6b00a348-593f-4130-90b2-3000097dc3c2.png)

**Comment by reonZ** [comment]
![firefox_zbsYATMtcS](https://user-images.githubusercontent.com/651462/235766208-4acca757-97ee-43d4-b599-80a607d457b8.jpg)

You do not have a GM online, that is why you can't make the transfer.

**Comment by reonZ** [comment]
I will assume your problem is resolved considering you haven't given me any news.

**Comment by xavien12** [comment]
Yes the problem was solved. Thank you.
